trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'
  
steps:
  
  - task: Npm@1
    displayName: 'Publish to npm'
    inputs:
      command: publish
      publishRegistry: useExternalRegistry
      publishEndpoint: 'NpmPlaywright'