trigger:
  branches:
    include:
      - master
  tags:
    include:
      - release/*
pr: none
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Npm@1
    displayName: 'run npm ci'
    inputs:
      command: ci
  - task: Npm@1
    displayName: 'Build'
    inputs:
      command: custom
      customCommand: run build
  - task: Npm@1
    displayName: 'Publish to npm'
    inputs:
      command: custom
      customCommand: publish --access public
      publishRegistry: useExternalRegistry
      publishEndpoint: NpmPlaywright
      customEndpoint: NpmPlaywright